/*********************************************************
 * MEANINGS — short upright/reversed keywords for all 78
 * tarot cards plus runes. Used by the tap-hold desc overlay.
 *********************************************************/
window.Meanings = (() => {

  const data = {
    // ── Major Arcana ──────────────────────────────────────
    "The Fool":            ["New beginnings, innocence, spontaneity, a free spirit",
                            "Naivety, foolishness, recklessness, risk-taking"],
    "The Magician":        ["Willpower, skill, resourcefulness, manifestation",
                            "Manipulation, poor planning, untapped talents"],
    "The High Priestess":  ["Intuition, sacred knowledge, the subconscious",
                            "Secrets, disconnection from intuition, withdrawal"],
    "The Empress":         ["Femininity, beauty, nature, abundance, nurturing",
                            "Creative block, dependence, smothering"],
    "The Emperor":         ["Authority, structure, fatherhood, stability",
                            "Domination, rigidity, inflexibility, control"],
    "The Hierophant":      ["Tradition, conformity, spirituality, institutions",
                            "Rebellion, subversiveness, new approaches"],
    "The Lovers":          ["Love, harmony, relationships, choices, alignment",
                            "Disharmony, imbalance, misalignment of values"],
    "The Chariot":         ["Control, willpower, victory, determination",
                            "Lack of control, aggression, no direction"],
    "Strength":            ["Courage, patience, inner strength, compassion",
                            "Inner doubt, low energy, self-doubt, weakness"],
    "The Hermit":          ["Introspection, solitude, inner guidance, wisdom",
                            "Isolation, loneliness, withdrawal, rejection"],
    "Wheel of Fortune":    ["Luck, cycles, fate, turning point",
                            "Bad luck, resistance to change, breaking cycles"],
    "Justice":             ["Justice, fairness, truth, cause and effect",
                            "Unfairness, dishonesty, lack of accountability"],
    "The Hanged Man":      ["Surrender, new perspectives, enlightenment, waiting",
                            "Delays, resistance, stalling, indecision"],
    "Death":               ["Endings, beginnings, change, transition, letting go",
                            "Resistance to change, inability to move on"],
    "Temperance":          ["Balance, moderation, patience, purpose",
                            "Imbalance, excess, lack of long-term vision"],
    "The Devil":           ["Bondage, materialism, ignorance, shadow self",
                            "Releasing limiting beliefs, detachment, freedom"],
    "The Tower":           ["Sudden upheaval, chaos, revelation, awakening",
                            "Averting disaster, fear of change, delaying"],
    "The Star":            ["Hope, faith, renewal, inspiration, serenity",
                            "Faithlessness, discouragement, insecurity"],
    "The Moon":            ["Illusion, fear, the unconscious, confusion",
                            "Release of fear, confusion lifts, misunderstanding"],
    "The Sun":             ["Success, radiance, abundance, joy, optimism",
                            "Temporary depression, positivity blocked, sadness"],
    "Judgement":           ["Reflection, reckoning, awakening, inner calling",
                            "Self-doubt, refusal of self-examination, malicious"],
    "The World":           ["Completion, integration, accomplishment, travel",
                            "Seeking closure, shortcuts, delays, incomplete work"],

    // ── Wands ─────────────────────────────────────────────
    "Ace of Wands":        ["Inspiration, new opportunities, growth, potential",
                            "Delays, lack of motivation, weighed down"],
    "Two of Wands":        ["Planning, making decisions, leaving home, expansion",
                            "Fear of unknown, indecision, playing it safe"],
    "Three of Wands":      ["Looking ahead, expansion, foresight, long-term plans",
                            "Obstacles, delays, disappointing results"],
    "Four of Wands":       ["Celebration, harmony, home, community",
                            "Personal celebration, lack of support, transience"],
    "Five of Wands":       ["Conflict, disagreements, competition, tension",
                            "Avoiding conflict, respecting differences"],
    "Six of Wands":        ["Victory, success, public reward, progress",
                            "Egotism, fall from grace, opposition"],
    "Seven of Wands":      ["Challenge, competition, perseverance, holding ground",
                            "Giving up, overwhelmed, self-doubt"],
    "Eight of Wands":      ["Speed, action, air travel, communication, movement",
                            "Delays, frustration, holding off, internal alignment"],
    "Nine of Wands":       ["Resilience, grit, last stand, persistence",
                            "Exhaustion, fatigue, questioning, reluctance"],
    "Ten of Wands":        ["Burden, extra responsibility, hard work, completion",
                            "Doing it all, carrying the load, burnt out"],
    "Page of Wands":       ["Enthusiasm, exploration, discovery, free spirit",
                            "Newness, immaturity, lack of direction"],
    "Knight of Wands":     ["Energy, passion, inspired action, adventure",
                            "Passion without purpose, haste, scattered energy"],
    "Queen of Wands":      ["Courage, confidence, independence, determination",
                            "Selfishness, jealousy, insecurities, dependence"],
    "King of Wands":       ["Natural-born leader, vision, entrepreneur, bold",
                            "Impulsiveness, overbearing, unachievable expectations"],

    // ── Cups ──────────────────────────────────────────────
    "Ace of Cups":         ["Compassion, creativity, overwhelming emotion, new love",
                            "Self-love, intuition blocked, emptiness"],
    "Two of Cups":         ["Unity, partnership, mutual attraction, connection",
                            "Imbalance, broken communication, tension"],
    "Three of Cups":       ["Friendship, community, reunions, celebration",
                            "Gossip, excess, independence, alone time"],
    "Four of Cups":        ["Meditation, apathy, contemplation, reevaluation",
                            "Retreat, withdrawal, checking in, missed opportunity"],
    "Five of Cups":        ["Regret, failure, disappointment, pessimism",
                            "Moving on, acceptance, forgiveness"],
    "Six of Cups":         ["Revisiting the past, nostalgia, reunion, childhood",
                            "Living in the past, unrealistic, naivety"],
    "Seven of Cups":       ["Choices, wishful thinking, illusion, fantasy",
                            "Alignment, clarity, decisive choices"],
    "Eight of Cups":       ["Walking away, disillusionment, abandonment",
                            "Avoidance, fear of moving on, staying in a rut"],
    "Nine of Cups":        ["Contentment, satisfaction, gratitude, wish come true",
                            "Overindulgence, materialism, dissatisfaction"],
    "Ten of Cups":         ["Happiness, marriage, alignment, family, harmony",
                            "Broken family, disconnection, misaligned values"],
    "Page of Cups":        ["Dreamy, sensitive, creative, a message of love",
                            "Emotional immaturity, insecurity, disappointment"],
    "Knight of Cups":      ["Romance, charm, imagination, following your heart",
                            "Unrealistic, jealousy, moodiness, illusion"],
    "Queen of Cups":       ["Compassion, calm, comfort, intuition, emotional",
                            "Martyrdom, insecurity, giving too much"],
    "King of Cups":        ["Emotionally balanced, diplomatic, compassionate",
                            "Manipulation, moodiness, emotionally volatile"],

    // ── Swords ────────────────────────────────────────────
    "Ace of Swords":       ["Breakthroughs, clarity, sharp mind, new idea",
                            "Confusion, brutality, chaos"],
    "Two of Swords":       ["Indecision, choices, truce, stalemate",
                            "Indecision, confusion, information overload"],
    "Three of Swords":     ["Heartbreak, grief, hurt, sorrow, sadness",
                            "Recovering, forgiveness, moving on"],
    "Four of Swords":      ["Rest, relaxation, meditation, sanctuary, recovery",
                            "Restlessness, burn-out, stress, exhaustion"],
    "Five of Swords":      ["Conflict, tension, defeat, winning at all costs",
                            "Reconciliation, making amends, change"],
    "Six of Swords":       ["Transition, change, rite of passage, releasing",
                            "Resistance to change, unfinished business"],
    "Seven of Swords":     ["Betrayal, deception, getting away with something",
                            "Imposter syndrome, coming clean, conscience"],
    "Eight of Swords":     ["Imprisonment, entrapment, victim mentality, self-limiting",
                            "Freedom, self-acceptance, release, open mind"],
    "Nine of Swords":      ["Anxiety, worry, fear, depression, nightmares",
                            "Hope, reaching out, light at end of tunnel"],
    "Ten of Swords":       ["Painful endings, betrayal, crisis, collapse",
                            "Recovery, regeneration, resisting inevitable end"],
    "Page of Swords":      ["Curious, communicative, thirst for knowledge",
                            "Deception, manipulation, talking without listening"],
    "Knight of Swords":    ["Ambitious, action-oriented, driven, fast-thinking",
                            "Restless, scattered, impatient, impulsive"],
    "Queen of Swords":     ["Independent, unbiased, clear boundaries, honest",
                            "Cold-hearted, cruel, bitter, resentful"],
    "King of Swords":      ["Mental clarity, intellectual power, authority, truth",
                            "Manipulative, tyrannical, abusive, irrational"],

    // ── Pentacles ─────────────────────────────────────────
    "Ace of Pentacles":    ["Opportunity, prosperity, new venture, abundance",
                            "Lost opportunity, missed chances, scarcity"],
    "Two of Pentacles":    ["Multiple priorities, time management, adaptable",
                            "Over-committed, disorganisation, poor balance"],
    "Three of Pentacles":  ["Teamwork, initial fulfilment, collaboration",
                            "Lack of teamwork, disorganised, conflict"],
    "Four of Pentacles":   ["Saving, security, conservatism, hoarding",
                            "Greediness, materialism, self-protection"],
    "Five of Pentacles":   ["Financial loss, poverty, lack, insecurity",
                            "Recovery, charity, improvement, spiritual poverty"],
    "Six of Pentacles":    ["Generosity, charity, giving, prosperity, sharing",
                            "Debt, selfishness, strings attached"],
    "Seven of Pentacles":  ["Long-term view, sustainable results, perseverance",
                            "Lack of long-term vision, limited reward"],
    "Eight of Pentacles":  ["Apprenticeship, repetitive tasks, mastery, skill",
                            "Self-development, perfectionism, misdirected"],
    "Nine of Pentacles":   ["Abundance, luxury, self-sufficiency, financial",
                            "Working too hard, financial setbacks, over-investment"],
    "Ten of Pentacles":    ["Wealth, financial security, long-term success",
                            "Family disputes, financial failure, bankruptcy"],
    "Page of Pentacles":   ["Manifestation, financial opportunity, skill",
                            "Lack of progress, procrastination, short-term"],
    "Knight of Pentacles": ["Efficiency, routine, health, conservative",
                            "Self-discipline, boredom, feeling stuck, perfectionism"],
    "Queen of Pentacles":  ["Practicality, creature comforts, financial security",
                            "Self-centeredness, jealousy, smothering, work-life"],
    "King of Pentacles":   ["Wealth, business, leadership, security, discipline",
                            "Financially inept, obsessed with wealth, stubborn"],

    // ── Runes (Elder Futhark) ─────────────────────────────
    "Fehu":    ["Wealth, abundance, prosperity, luck, success", "Loss, greed, stagnation"],
    "Uruz":    ["Strength, vitality, primal force, endurance", "Weakness, poor health, stubbornness"],
    "Thurisaz":["Protection, conflict, change, chaos, gateway", "Danger, defenselessness, betrayal"],
    "Ansuz":   ["Wisdom, communication, inspiration, truth", "Miscommunication, deception, confusion"],
    "Raidho":  ["Journey, movement, growth, perspective", "Stagnation, delay, recklessness"],
    "Kenaz":   ["Knowledge, creativity, vision, clarity, fire", "Ignorance, fear, false hope"],
    "Gebo":    ["Partnership, generosity, exchange, gifts", "Imbalance, obligation, isolation"],
    "Wunjo":   ["Joy, harmony, fellowship, success, pleasure", "Sorrow, alienation, discord"],
    "Hagalaz": ["Disruption, testing, hail storm, change", "Stagnation, powerlessness, crisis"],
    "Nauthiz": ["Need, restriction, survival, endurance", "Constraint, necessity, frustration"],
    "Isa":     ["Stillness, clarity, patience, introspection", "Stagnation, ego, frozen"],
    "Jera":    ["Harvest, reward, cycles, natural timing", "Setback, poor timing, conflict"],
    "Eihwaz":  ["Endurance, defence, transformation, reliability", "Confusion, weakness, duplicity"],
    "Perthro": ["Fate, mystery, chance, divination", "Stagnation, addiction, loneliness"],
    "Algiz":   ["Protection, warding, higher self, sanctuary", "Vulnerability, danger, hidden"],
    "Sowilo":  ["Sun, success, wholeness, vitality, life force", "False goals, overconfidence, low energy"],
    "Tiwaz":   ["Honour, justice, leadership, sacrifice, victory", "Defeat, injustice, cowardice"],
    "Berkano": ["Birch, fertility, growth, renewal, femininity", "Stagnation, loss, domestic trouble"],
    "Ehwaz":   ["Movement, partnership, progress, trust, horse", "Haste, betrayal, instability"],
    "Mannaz":  ["Humanity, self, community, intelligence", "Isolation, self-deceit, manipulation"],
    "Laguz":   ["Water, flow, intuition, the unknown, renewal", "Fear, confusion, blocked intuition"],
    "Ingwaz":  ["Fertility, new beginnings, gestation, inner growth", "Impotence, stagnation, wasted energy"],
    "Dagaz":   ["Breakthrough, awakening, clarity, hope, day", "Obscurity, confusion, delays"],
    "Othala":  ["Inheritance, heritage, home, tradition, ancestry", "Prejudice, poverty, homelessness"],
  };

  function get(name, reversed) {
    // Strip reversal suffix for lookup
    const clean = name.replace(/ \(R\)$/, "");
    const entry = data[clean];
    if (!entry) return reversed
      ? "A mystery card. Its reversed meaning is hidden."
      : "A mystery card. Its meaning is yet to be revealed.";
    return reversed ? entry[1] : entry[0];
  }

  return { get };

})();
